---
project: billiam_database

ignore_patterns: ["__*.sql"]
default_target_environment: dev
model_defaults:
  dialect: duckdb
  start: 2018-01-01

plan:
  enable_preview: true

default_gateway: local
gateways:
  local:
    connection:
      type: duckdb
      catalogs:
        billiam: "billiam_database/billiam.duckdb"
        ods:
          type: motherduck
          path: "md:ods?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
  motherduck:
    connection:
      type: motherduck
      token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
      catalogs:
        warehouse: warehouse
        ods: ods
