---
project: billiam_database

ignore_patterns: ["__*.sql"]
default_target_environment: dev
model_defaults:
  dialect: duckdb
  start: 2018-01-01

plan:
  enable_preview: true

default_gateway: local
gateways:
  local:
    connection:
      type: duckdb
      database: billiam_database/billiam.duckdb
  motherduck:
    connection:
      type: motherduck
      database: warehouse
      token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
